#!/usr/local/bin/python3.4 -u

# To be able to launch the script from the DOCK, you'll need to set the
# environment variable "PYTHONPATH" by launchctl
# Take a look at ~/Library/LaunchAgents/setenv.PYTHONPATH.plist

# Why <LSEnvironment> in Info.plist doesn't work??

from PyQt5 import QtCore, QtGui, QtWidgets
import os, sys
import mainwidget
import appobj

if __name__ == "__main__":
  app = QtWidgets.QApplication(sys.argv)
  mctrl = appobj.MusyncController()
  gui = mainwidget.MusyncGUI(mctrl)
  gui.show()
  sys.exit(app.exec_())
